### ISSUE TITLE
error "Cannot read property 'disassociate' of undefined" when trigering Failover

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#5]
(Issue moved from https://github.com/f5devcentral/f5-cloud-failover-extension/issues/22)

Reported By: @tewfikm 

from Version CFE : v1.1
TITLE: When trigering failover Severe error "severe: [f5-cloud-failover] failover.execute() error: Cannot read property 'disassociate' of undefined TypeError: Cannot read property 'disassociate' of undefined"
is generated.

version impacted:

{
"version": "1.1.0",
"release": "0",
"schemaCurrent": "1.1.0",
"schemaMinimum": "0.9.1"
}

MSI:
OK

Details:
on Unit1:
Wed, 25 Mar 2020 15:39:29 GMT - finest: socket 206 closed
Wed, 25 Mar 2020 15:53:59 GMT - finest: socket 207 opened
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing failover - execute
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing Failover - recovery
Wed, 25 Mar 2020 15:54:02 GMT - warning: [f5-cloud-failover] Recovering previous task: {"routes":{"operations":[]}}
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing Failover - update
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] No localAddresses/failoverAddresses to discover
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] No route operations to run
Wed, 25 Mar 2020 15:54:02 GMT - severe: [f5-cloud-failover] failover.execute() error: Cannot read property 'disassociate' of undefined TypeError: Cannot read property 'disassociate' of undefined
at _discoverAddressOperations.then.operations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/azure/cloud.js:129:66)
at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
Wed, 25 Mar 2020 15:54:07 GMT - finest: socket 207 closed

on Unit2:
Wed, 25 Mar 2020 15:39:29 GMT - finest: socket 206 closed
Wed, 25 Mar 2020 15:53:59 GMT - finest: socket 207 opened
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing failover - execute
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing Failover - recovery
Wed, 25 Mar 2020 15:54:02 GMT - warning: [f5-cloud-failover] Recovering previous task: {"routes":{"operations":[]}}
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] Performing Failover - update
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] No localAddresses/failoverAddresses to discover
Wed, 25 Mar 2020 15:54:02 GMT - info: [f5-cloud-failover] No route operations to run
Wed, 25 Mar 2020 15:54:02 GMT - severe: [f5-cloud-failover] failover.execute() error: Cannot read property 'disassociate' of undefined TypeError: Cannot read property 'disassociate' of undefined
at _discoverAddressOperations.then.operations (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/azure/cloud.js:129:66)
at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:794:20)
at tryOnImmediate (timers.js:752:5)
at processImmediate [as _immediateCallback] (timers.js:729:5)
Wed, 25 Mar 2020 15:54:07 GMT - finest: socket 207 closed

**Comment by alaari-f5** [comment]
Thank you for reporting this issue. Internal issue AUTOSDK-251 has been created for this enhancement.

**Comment by shyawnkarim** [comment]
@tewfikm with CFE 1.2 we have implemented a lot more error handling. Is this issue still happening with 1.2?

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with release 1.2.
