### ISSUE TITLE
Error 400, failed to download custom config

### ISSUE THREAD

**Issue by dcristobalh** [F5Networks/f5-cloud-failover-extension#88]
## Description
Cannot deploy cloud-failover rpm with azure_deployment template and output java errors

`Failed to download custom config; continuing with response code '000' Application deployment failed or custom URL was not specified. Failed to deploy CFE application with response code '{"code":400,"message":"remoteSender:127.0.0.1, method:POST ","originalRequestBody"....`

After our data in json format...

`referer":"127.0.0.1","restOperationId":1612879,"errorStack":["java.util.concurrent.TimeoutException: remoteSender:127.0.0.1, method:POST ","at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3168)","at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3157)","at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1263)","at com.f5.rest.common.RestServer.access$200(RestServer.java:44)","at com.f5.rest.common.RestServer$3.run(RestServer.java:1236)","at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)","at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)","at java.util.concurrent.FutureTask.run(FutureTask.java:262)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)","at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)","at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)","at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)","at java.lang.Thread.run(Thread.java:748)\n"],"kind":":resterrorresponse"}400'`

## Environment information
For bugs, enter the following information:
- Cloud Failover Extension Version: 1.7.1-1
- BIG-IP version: latest
- Cloud provider: Azure

## Severity Level

Severity: 2

**Comment by dcristobalh** [comment]
I answer myself, the problem with this error was our DNS server
